export const UPDATED_CART = 'UPDATED_CART';
export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';
export const SET_UNAUTHENTICATED = 'SET_UNAUTHENTICATED';
export const SET_AUTHENTICATED_ADMIN = 'SET_AUTHENTICATED_ADMIN';
export const SET_UNAUTHENTICATED_ADMIN = 'SET_UNAUTHENTICATED_ADMIN';